export const bookGenres = [
  // Fiction
  { value: "fantasy", label: "Fantasy" },
  { value: "science-fiction", label: "Science Fiction" },
  { value: "dystopian", label: "Dystopian" },
  { value: "adventure", label: "Adventure" },
  { value: "mystery", label: "Mystery" },
  { value: "thriller", label: "Thriller" },
  { value: "horror", label: "Horror" },
  { value: "historical-fiction", label: "Historical Fiction" },
  { value: "romance", label: "Romance" },
  { value: "contemporary", label: "Contemporary" },
  { value: "childrens-fiction", label: "Children’s Fiction" },
  { value: "graphic-novel-comics", label: "Graphic Novel / Comics" },
  { value: "short-stories", label: "Short Stories" },

  // Non-Fiction
  { value: "biography", label: "Biography" },
  { value: "autobiography", label: "Autobiography" },
  { value: "memoir", label: "Memoir" },
  { value: "history", label: "History" },
  { value: "self-help", label: "Self-Help" },
  { value: "philosophy", label: "Philosophy" },
  { value: "psychology", label: "Psychology" },
  { value: "science-technology", label: "Science & Technology" },
  { value: "travel", label: "Travel" },
  { value: "true-crime", label: "True Crime" },
  { value: "politics", label: "Politics" },
  { value: "religion-spirituality", label: "Religion / Spirituality" },
  { value: "business-economics", label: "Business / Economics" },
  { value: "health-wellness", label: "Health & Wellness" },
  { value: "education-academic", label: "Education / Academic" },
  { value: "essays", label: "Essays" },
];
